"""empty message

Revision ID: 6d54f522cea8
Revises: e5b3083e8abd
Create Date: 2021-03-28 10:51:50.487378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d54f522cea8'
down_revision = 'e5b3083e8abd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('test', sa.VARCHAR(length=120), nullable=False))
    # ### end Alembic commands ###
