"""empty message

Revision ID: 8205d3c2ad65
Revises: 6d54f522cea8
Create Date: 2021-03-28 10:56:24.066532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8205d3c2ad65'
down_revision = '6d54f522cea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tet', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tet')
    # ### end Alembic commands ###
