"""empty message

Revision ID: e5b3083e8abd
Revises: 841694e3d6e9
Create Date: 2021-03-28 10:41:28.096389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b3083e8abd'
down_revision = '841694e3d6e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=75), nullable=False),
    sa.Column('location', sa.String(length=25), nullable=False),
    sa.Column('timeText', sa.String(length=25), nullable=False),
    sa.Column('dateText', sa.String(length=25), nullable=False),
    sa.Column('date', sa.DateTime(timezone=40), nullable=False),
    sa.Column('time', sa.Time(timezone=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailing_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=25), nullable=False),
    sa.Column('date', sa.DateTime(timezone=40), nullable=False),
    sa.Column('dateText', sa.String(length=25), nullable=False),
    sa.Column('timeText', sa.String(length=25), nullable=False),
    sa.Column('time', sa.Time(timezone=40), nullable=False),
    sa.Column('link', sa.String(length=120), nullable=False),
    sa.Column('test', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('imageFile', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('meeting')
    op.drop_table('mailing_list')
    op.drop_table('event')
    # ### end Alembic commands ###
